//! The About window: a separate top-level window, created only on request and reused if already
//! open, never on the startup path. Laid out after concept sheet 5
//! (`docs/design/concepts/sheet-5-about-window.webp`): the stacked logo, the tagline, the
//! "Faster than light" divider, the product facts, then environment facts useful for support
//! requests. The logo is the one piece of brand artwork in the app (owner-approved, see
//! `docs/design/DESIGN_DIRECTION.md`), rasterized only when this window opens.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use gpui::{
    App, Bounds, ClipboardItem, Context, FocusHandle, Focusable, FontWeight, Global, Image,
    ImageFormat, IntoElement, KeyDownEvent, ObjectFit, Pixels, Render, SharedString, Size,
    StyledImage as _, TitlebarOptions, Window, WindowBounds, WindowHandle, WindowOptions, actions,
    div, img, prelude::*, px, size,
};

use crate::backup::Backups;
use crate::editor::CloseWindow;
use crate::settings::SettingsFile;
use crate::theme::Theme;

actions!(about, [About]);

/// The window's app id (X11/Wayland grouping): the same value `tachyon::app::APP_ID` uses. A
/// literal here rather than a shared constant, since a compositor only uses it to group windows
/// and `tachyon-editor` does not otherwise depend on the binary crate.
const APP_ID: &str = "tachyon";

const ABOUT_SIZE: Size<Pixels> = size(px(440.), px(760.));

/// Room kept free for the frame and title bar around the window's content, the same allowance the
/// editor windows keep (`FRAME_ALLOWANCE` in `tachyon::app`; a literal here for the reason given at
/// [`APP_ID`]). Windows adds the frame outside the client area GPUI sizes.
const FRAME_ALLOWANCE: Pixels = px(48.);

/// The stacked lockup (gradient symbol above the wordmark), generated by
/// `scripts/brand/compose.py`: navy wordmark for the light theme, white for the dark. Declared at
/// twice [`LOCKUP_WIDTH`], because GPUI rasterizes an SVG image once at its declared size.
const LOCKUP_LIGHT_THEME: &[u8] = include_bytes!("../../../assets/brand/about-lockup.svg");
const LOCKUP_DARK_THEME: &[u8] = include_bytes!("../../../assets/brand/about-lockup-white.svg");
/// The lockup's display width; `ABOUT_LOCKUP_WIDTH` in `scripts/brand/compose.py` must match.
const LOCKUP_WIDTH: Pixels = px(220.);

/// The owner's tagline for the About window (concept sheet 5), in the design system's voice.
const TAGLINE: &str = "A markdown editor built for instant startup and distraction-free writing.";
/// The divider's label, letter-spaced with thin spaces (U+2009): GPUI text has no letter-spacing
/// setting, and the design system tracks these labels out by about a quarter of an em.
const DIVIDER_LABEL: &str = "F\u{2009}A\u{2009}S\u{2009}T\u{2009}E\u{2009}R \u{2009}T\u{2009}H\u{2009}A\u{2009}N \u{2009}L\u{2009}I\u{2009}G\u{2009}H\u{2009}T";

const SUPPORT_LABEL: &str = "github.com/DailenG/tachyon/issues";
const SUPPORT_URL: &str = "https://github.com/DailenG/tachyon/issues";
const WEBSITE_LABEL: &str = "daileng.github.io/tachyon";
const WEBSITE_URL: &str = "https://daileng.github.io/tachyon";
const SOURCE_LABEL: &str = "github.com/DailenG/tachyon";
const SOURCE_URL: &str = "https://github.com/DailenG/tachyon";
const LICENSE: &str = "MIT OR Apache-2.0";

/// Facts about this process that only the binary which started it knows: its own crate version
/// (`tachyon`, not `tachyon-editor`'s) and whether it stays resident after its last window
/// closes. Set once at start-up so [`About`] - dispatched with no other context, from the tray,
/// the command palette, or `--about` - and the window it opens can read them without every
/// caller threading them through. Not set by tests that never run the application's start-up;
/// [`AboutView::new`] falls back to sensible defaults then.
pub struct AppInfo {
    pub version: SharedString,
    pub resident: bool,
}

impl Global for AppInfo {}

/// The one About window, if it is open, so a second request focuses it instead of opening
/// another.
#[derive(Default)]
struct AboutWindowHandle(Option<WindowHandle<AboutView>>);

impl Global for AboutWindowHandle {}

/// Opens the About window, or brings the existing one to the front if it is already open.
pub fn open_about(cx: &mut App) -> Option<WindowHandle<AboutView>> {
    if let Some(handle) = cx.try_global::<AboutWindowHandle>().and_then(|h| h.0)
        && handle.update(cx, |_, window, _| window.activate_window()).is_ok()
    {
        return Some(handle);
    }
    let handle = create_window(cx)?;
    cx.set_global(AboutWindowHandle(Some(handle)));
    Some(handle)
}

fn create_window(cx: &mut App) -> Option<WindowHandle<AboutView>> {
    let bounds = match cx.primary_display() {
        Some(display) => fit_about(display.visible_bounds()),
        None => Bounds::centered(None, ABOUT_SIZE, cx),
    };
    let options = WindowOptions {
        window_bounds: Some(WindowBounds::Windowed(bounds)),
        titlebar: Some(TitlebarOptions {
            title: Some("About Tachyon".into()),
            ..Default::default()
        }),
        app_id: Some(APP_ID.to_owned()),
        is_resizable: false,
        show: true,
        focus: true,
        ..Default::default()
    };
    let result = cx.open_window(options, |window, cx| {
        tachyon_platform::set_window_icon(window);
        let theme = Theme::for_window(window, cx);
        tachyon_platform::set_title_bar_dark(window, theme.dark);
        cx.new(|cx| AboutView::new(theme, window, cx))
    });
    match result {
        Ok(handle) => Some(handle),
        Err(e) => {
            eprintln!("tachyon: failed to open the About window: {e:#}");
            None
        }
    }
}

/// [`ABOUT_SIZE`] centered in `work_area`, shortened to fit there with its frame: a 1080p screen at
/// 150 % has under 700 px of work area. The body scrolls when shortened, and the buttons stay
/// below it, so they are always reachable.
fn fit_about(work_area: Bounds<Pixels>) -> Bounds<Pixels> {
    let height = ABOUT_SIZE.height.min(work_area.size.height - FRAME_ALLOWANCE).max(px(1.));
    Bounds::centered_at(work_area.center(), size(ABOUT_SIZE.width, height))
}

/// The About window's content.
pub struct AboutView {
    theme: Theme,
    focus: FocusHandle,
    logo: Arc<Image>,
    version: SharedString,
    packaged_version: Option<String>,
    resident: bool,
    platform: String,
    settings_path: Option<PathBuf>,
    backups_dir: Option<PathBuf>,
}

impl AboutView {
    fn new(theme: Theme, window: &mut Window, cx: &mut Context<Self>) -> Self {
        let focus = cx.focus_handle();
        window.focus(&focus, cx);
        let logo_bytes = if theme.dark { LOCKUP_DARK_THEME } else { LOCKUP_LIGHT_THEME };
        let (version, resident) = cx
            .try_global::<AppInfo>()
            .map(|info| (info.version.clone(), info.resident))
            .unwrap_or_else(|| (env!("CARGO_PKG_VERSION").into(), false));
        AboutView {
            theme,
            focus,
            logo: Arc::new(Image::from_bytes(ImageFormat::Svg, logo_bytes.to_vec())),
            version,
            packaged_version: tachyon_platform::packaged_version(),
            resident,
            platform: tachyon_platform::os_version(),
            settings_path: cx.try_global::<SettingsFile>().map(|f| f.0.clone()),
            backups_dir: cx.try_global::<Backups>().map(|b| b.dir().to_path_buf()),
        }
    }

    fn install(&self) -> &'static str {
        if self.packaged_version.is_some() { "Installed package" } else { "Portable" }
    }

    fn mode(&self) -> &'static str {
        if self.resident { "Resident" } else { "Standalone" }
    }

    /// "Stable"/"Nightly" come from the packaged version's build number (the fourth part of
    /// `X.Y.Z.B`; see `docs/adr/0007-versions-and-release-channels.md`): `B = 0` is a stable
    /// release, anything else a nightly build. A portable build checks nothing, so it says so.
    fn updates(&self) -> &'static str {
        match &self.packaged_version {
            Some(version) => {
                let build: Option<u32> = version.rsplit('.').next().and_then(|b| b.parse().ok());
                if build == Some(0) { "Stable, automatic" } else { "Nightly, automatic" }
            }
            None => "Manual",
        }
    }

    fn path_text(path: Option<&PathBuf>) -> String {
        path.map_or_else(|| "not available".to_owned(), |p| p.display().to_string())
    }

    /// The Environment table as plain text, for the "Copy details" button and support requests.
    pub(crate) fn environment_text(&self) -> String {
        let mut text = format!("Tachyon {}\n", self.version);
        if let Some(package) = &self.packaged_version {
            text.push_str(&format!("Package {package}\n"));
        }
        text.push_str(&format!(
            "Platform: {}\nInstall: {}\nMode: {}\nUpdates: {}\nSettings: {}\nBackups: {}\n\
             Website: {WEBSITE_URL}\n",
            self.platform,
            self.install(),
            self.mode(),
            self.updates(),
            Self::path_text(self.settings_path.as_ref()),
            Self::path_text(self.backups_dir.as_ref()),
        ));
        text
    }

    fn key_down(&mut self, event: &KeyDownEvent, window: &mut Window, cx: &mut Context<Self>) {
        if event.keystroke.key.as_str() == "escape" {
            window.remove_window();
            cx.stop_propagation();
        }
    }

    fn close_window(&mut self, _: &CloseWindow, window: &mut Window, _: &mut Context<Self>) {
        window.remove_window();
    }

    fn copy_details(&mut self, _: &gpui::ClickEvent, _: &mut Window, cx: &mut Context<Self>) {
        cx.write_to_clipboard(ClipboardItem::new_string(self.environment_text()));
    }
}

impl Focusable for AboutView {
    fn focus_handle(&self, _: &App) -> FocusHandle {
        self.focus.clone()
    }
}

impl Render for AboutView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let theme = self.theme.clone();

        fn row(theme: &Theme, label_text: &'static str, value: impl IntoElement) -> gpui::Div {
            let label =
                div().w(px(84.)).flex_shrink_0().text_color(theme.text.muted).child(label_text);
            div().w_full().flex().flex_row().gap_2().child(label).child(value)
        }
        let value = |theme: &Theme, text: String| div().text_color(theme.text.primary).child(text);
        let link = |theme: &Theme, id: &'static str, text: String| {
            div().id(id).cursor_pointer().text_color(theme.text.link).underline().child(text)
        };
        // A path is often wider than the window: shown with `~` for the home folder and cut in
        // the middle, so both the drive or home and the file name stay visible. Clicking still
        // reveals the real path, and Copy details has it in full.
        let path_cell = |theme: &Theme, id: &'static str, path: Option<PathBuf>| match path {
            Some(path) => link(theme, id, display_path(&path))
                .flex_1()
                .min_w_0()
                .overflow_hidden()
                .whitespace_nowrap()
                .text_ellipsis_middle()
                .on_click(cx.listener(move |_, _, _, cx| cx.reveal_path(&path)))
                .into_any_element(),
            None => value(theme, "not available".to_owned()).into_any_element(),
        };

        let version = match &self.packaged_version {
            Some(package) => format!("{} (package {package})", self.version),
            None => self.version.to_string(),
        };
        let rule = |theme: &Theme| div().flex_1().h(px(1.)).bg(theme.border.subtle);
        let section = |theme: &Theme, title: &'static str| {
            div()
                .w_full()
                .mt_2()
                .font_weight(FontWeight::BOLD)
                .text_color(theme.text.muted)
                .child(title)
        };

        // Everything above the buttons, at its natural height. In a flex column the logo would
        // shrink instead of overflowing, so this sits in its own scroll container below.
        let content = div()
            .w_full()
            .flex()
            .flex_col()
            .items_center()
            .gap_2()
            .child(
                img(self.logo.clone())
                    .w(LOCKUP_WIDTH)
                    .h(LOCKUP_WIDTH * 0.72)
                    .object_fit(ObjectFit::Contain),
            )
            .child(
                div().w(px(320.)).mt_2().text_center().text_color(theme.text.muted).child(TAGLINE),
            )
            // The divider: a solid accent label between two hairlines. Solid colors only in the
            // app (DESIGN_DIRECTION.md); the gradient rule is for the website.
            .child(
                div()
                    .w_full()
                    .my_2()
                    .flex()
                    .flex_row()
                    .items_center()
                    .gap_3()
                    .child(rule(&theme))
                    .child(
                        div()
                            .flex_none()
                            .text_size(theme.scaled(px(12.)))
                            .font_weight(FontWeight::SEMIBOLD)
                            .text_color(theme.accent)
                            .child(DIVIDER_LABEL),
                    )
                    .child(rule(&theme)),
            )
            .child(
                div()
                    .w_full()
                    .flex()
                    .flex_col()
                    .gap_1()
                    .child(row(&theme, "Version", value(&theme, version)))
                    .child(row(
                        &theme,
                        "Website",
                        link(&theme, "website-link", WEBSITE_LABEL.to_owned())
                            .on_click(cx.listener(|_, _, _, cx| cx.open_url(WEBSITE_URL))),
                    ))
                    .child(row(
                        &theme,
                        "Source",
                        link(&theme, "source-link", SOURCE_LABEL.to_owned())
                            .on_click(cx.listener(|_, _, _, cx| cx.open_url(SOURCE_URL))),
                    ))
                    .child(row(
                        &theme,
                        "Support",
                        link(&theme, "support-link", SUPPORT_LABEL.to_owned())
                            .on_click(cx.listener(|_, _, _, cx| cx.open_url(SUPPORT_URL))),
                    ))
                    .child(row(&theme, "License", value(&theme, LICENSE.to_owned())))
                    .child(row(&theme, "Author", value(&theme, "Dailen Gunter".to_owned()))),
            )
            .child(section(&theme, "Environment"))
            .child(
                div()
                    .w_full()
                    .flex()
                    .flex_col()
                    .gap_1()
                    .child(row(&theme, "Platform", value(&theme, self.platform.clone())))
                    .child(row(&theme, "Install", value(&theme, self.install().to_owned())))
                    .child(row(&theme, "Mode", value(&theme, self.mode().to_owned())))
                    .child(row(&theme, "Updates", value(&theme, self.updates().to_owned())))
                    .child(row(
                        &theme,
                        "Settings",
                        path_cell(&theme, "settings-path", self.settings_path.clone()),
                    ))
                    .child(row(
                        &theme,
                        "Backups",
                        path_cell(&theme, "backups-dir", self.backups_dir.clone()),
                    )),
            );
        // Scrolls only when the window was shortened to fit a small work area (`fit_about`); the
        // buttons below it stay in view.
        let body =
            div().id("about-body").w_full().flex_1().min_h_0().overflow_y_scroll().child(content);

        div()
            .size_full()
            .bg(theme.surface.canvas)
            .text_color(theme.text.primary)
            .font_family(theme.text_font.clone())
            .text_size(theme.text_size)
            .track_focus(&self.focus)
            .on_key_down(cx.listener(Self::key_down))
            .on_action(cx.listener(Self::close_window))
            .flex()
            .flex_col()
            .items_center()
            .p_6()
            .gap_2()
            .child(body)
            .child(
                div()
                    .w_full()
                    .flex()
                    .flex_row()
                    .justify_end()
                    .gap_2()
                    .mt_auto()
                    .child(
                        div()
                            .id("copy-details")
                            .px_3()
                            .py_1()
                            .rounded(theme.radius_small)
                            .border_1()
                            .cursor_pointer()
                            .border_color(theme.border.control)
                            .child("Copy details")
                            .on_click(cx.listener(Self::copy_details)),
                    )
                    .child(
                        div()
                            .id("close")
                            .px_3()
                            .py_1()
                            .rounded(theme.radius_small)
                            .border_1()
                            .cursor_pointer()
                            .border_color(theme.accent)
                            .bg(theme.accent)
                            .text_color(theme.text.on_accent)
                            .child("Close")
                            .on_click(cx.listener(|_, _, window, _| window.remove_window())),
                    ),
            )
    }
}

/// `path` with the home folder written as `~` (`HOME`, or `USERPROFILE` on Windows), for
/// display only.
fn display_path(path: &Path) -> String {
    let home = std::env::var_os(if cfg!(windows) { "USERPROFILE" } else { "HOME" });
    match home
        .map(PathBuf::from)
        .and_then(|home| path.strip_prefix(&home).ok().map(Path::to_path_buf))
    {
        Some(rest) => {
            let separator = std::path::MAIN_SEPARATOR;
            format!("~{separator}{}", rest.display())
        }
        None => path.display().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// GPUI rasterizes an SVG image once at its declared size, so the generated lockups must be
    /// declared at twice the width the window shows them at: `ABOUT_LOCKUP_WIDTH` in
    /// `scripts/brand/compose.py` and [`LOCKUP_WIDTH`] here have to agree.
    #[test]
    fn the_lockups_are_declared_at_twice_their_display_width() {
        for svg in [LOCKUP_LIGHT_THEME, LOCKUP_DARK_THEME] {
            let svg = std::str::from_utf8(svg).expect("the lockup is UTF-8 SVG");
            let width: f32 = svg
                .split("width=\"")
                .nth(1)
                .and_then(|rest| rest.split('"').next())
                .and_then(|w| w.parse().ok())
                .expect("the lockup declares a width");
            assert_eq!(width, f32::from(LOCKUP_WIDTH) * 2.0);
        }
    }

    /// A 1080p screen at 150 % with a 48 px taskbar: 1280 x 672 logical px of work area, less than
    /// the window's design height. The window must shrink to leave room for its frame and stay
    /// inside the work area, or the buttons end up under the taskbar.
    #[test]
    fn the_window_shrinks_to_fit_a_short_work_area() {
        let work_area =
            Bounds { origin: gpui::point(px(0.), px(0.)), size: size(px(1280.), px(672.)) };
        let bounds = fit_about(work_area);
        assert_eq!(bounds.size.height, px(672.) - FRAME_ALLOWANCE);
        assert_eq!(bounds.size.width, ABOUT_SIZE.width);
        assert!(bounds.origin.y >= work_area.origin.y);
        assert!(bounds.origin.y + bounds.size.height <= work_area.origin.y + work_area.size.height);
    }

    #[test]
    fn the_window_keeps_its_design_size_where_it_fits() {
        let work_area =
            Bounds { origin: gpui::point(px(-1920.), px(0.)), size: size(px(1920.), px(1032.)) };
        let bounds = fit_about(work_area);
        assert_eq!(bounds.size, ABOUT_SIZE);
        assert_eq!(bounds.center(), work_area.center());
    }
}
