//! Development tasks. Run with `cargo xtask <task>`.

use std::collections::BTreeMap;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;
use std::process::{Command, ExitCode, Stdio};
use std::sync::mpsc;
use std::time::{Duration, Instant};

const USAGE: &str = "\
Usage: cargo xtask <TASK>

Tasks:
  ci
      Runs the checks required by CI: rustfmt, clippy, tests and cargo-deny
      (when installed). Run before pushing.
  bench-startup [--warm [--gap-ms MS]] [--runs N] [--budget-ms MS] [--bin PATH] [--no-build]
      Launches the release binary N times (default 20) with --startup-report and
      reports spawn-to-first-frame latency. The first run is reported on its
      own (coldest caches); percentiles cover the other runs. Exits non-zero
      if their p95 exceeds the budget (default 50 ms).
      --warm measures launches handed to a resident instance instead: spawn of
      the second process until the resident instance has drawn the new window.
      --gap-ms waits between those launches (default 500, like a person; the
      resident instance prepares its next window in between).
  dist [--no-build]
      Builds the release binary and packs it with the README, changelog and
      licenses into target/dist/tachyon-<version>-<arch>-<os>.zip on Windows,
      .tar.gz elsewhere. --no-build skips the build and packs the binary
      already at target/release (used after signing it in place).
  icons
      Regenerates the application's icons from assets/brand: tachyon.ico (16-64 px,
      32-bit DIB images; the small icon art up to 32 px) and the launcher SVG, both in
      crates/tachyon-platform/assets. Needs rsvg-convert and ImageMagick (magick).
      Run after changing the brand art; the build only embeds the results.
  msix [--version X.Y.Z.W] [--appinstaller-base URL-OR-PATH]
      Windows only (needs makeappx.exe from the Windows 10/11 SDK). Packs
      target/release/tachyon.exe and packaging/msix/Assets (regenerated by
      `cargo xtask icons`) into target/dist/Tachyon_<version>_x64.msix, and
      writes target/dist/Tachyon.appinstaller for App Installer auto-update.
      --version overrides the manifest's 4-part version (workspace version
      + \".0\" by default; use a bumped 4th part to test that App Installer
      offers an update). --appinstaller-base overrides where the
      .appinstaller points (default the GitHub release URLs), for testing
      updates from another location.
";

const REPORT_PREFIX: &str = "tachyon-startup";
const RUN_TIMEOUT: Duration = Duration::from_secs(15);

fn main() -> ExitCode {
    let mut args = std::env::args().skip(1);
    let result = match args.next().as_deref() {
        Some("ci") => ci(args.collect()),
        Some("bench-startup") => bench_startup(args.collect()),
        Some("dist") => dist(args.collect()),
        Some("icons") => icons(),
        Some("msix") => msix(args.collect()),
        _ => {
            eprint!("{USAGE}");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(code) => code,
        Err(e) => {
            eprintln!("xtask: {e}");
            ExitCode::FAILURE
        }
    }
}

fn cargo() -> Command {
    let mut command = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()));
    command.current_dir(workspace_root());
    command
}

fn run_cargo(args: &[&str]) -> Result<(), String> {
    let line = format!("cargo {}", args.join(" "));
    eprintln!("$ {line}");
    let status = cargo().args(args).status().map_err(|e| format!("failed to run {line}: {e}"))?;
    if status.success() { Ok(()) } else { Err(format!("`{line}` failed")) }
}

/// Mirrors the required CI jobs so a green local run predicts a green PR.
fn ci(args: Vec<String>) -> Result<ExitCode, String> {
    if let Some(arg) = args.first() {
        return Err(format!("ci takes no arguments, got {arg}"));
    }
    run_cargo(&["fmt", "--all", "--check"])?;
    run_cargo(&["clippy", "--workspace", "--all-targets", "--locked", "--", "-D", "warnings"])?;
    run_cargo(&["test", "--workspace", "--locked"])?;
    if Command::new("cargo-deny").arg("--version").output().is_ok() {
        run_cargo(&["deny", "check"])?;
    } else {
        eprintln!(
            "xtask: cargo-deny is not installed; `cargo deny check` skipped (CI enforces it).\n\
             Install with: cargo install cargo-deny --locked"
        );
    }
    Ok(ExitCode::SUCCESS)
}

struct BenchOptions {
    runs: usize,
    budget: Duration,
    bin: Option<PathBuf>,
    build: bool,
    warm: bool,
    gap: Duration,
}

fn parse_bench_options(args: Vec<String>) -> Result<BenchOptions, String> {
    let mut options = BenchOptions {
        runs: 20,
        budget: Duration::from_millis(50),
        bin: None,
        build: true,
        warm: false,
        gap: Duration::from_millis(500),
    };
    let mut args = args.into_iter();
    while let Some(arg) = args.next() {
        let mut value = || args.next().ok_or_else(|| format!("{arg} needs a value"));
        match arg.as_str() {
            "--runs" => {
                options.runs = value()?.parse().map_err(|e| format!("--runs: {e}"))?;
                if options.runs == 0 {
                    return Err("--runs must be at least 1".into());
                }
            }
            "--budget-ms" => {
                let ms: u64 = value()?.parse().map_err(|e| format!("--budget-ms: {e}"))?;
                options.budget = Duration::from_millis(ms);
            }
            "--bin" => options.bin = Some(value()?.into()),
            "--no-build" => options.build = false,
            "--warm" => options.warm = true,
            "--gap-ms" => {
                let ms: u64 = value()?.parse().map_err(|e| format!("--gap-ms: {e}"))?;
                options.gap = Duration::from_millis(ms);
            }
            _ => return Err(format!("unknown argument {arg}\n\n{USAGE}")),
        }
    }
    Ok(options)
}

/// Files shipped next to the binary in a release archive.
const DIST_FILES: [&str; 4] = ["README.md", "CHANGELOG.md", "LICENSE-MIT", "LICENSE-APACHE"];

/// `--no-build` packs whatever is already at `target/release`, so CI can sign the binary (Windows
/// code signing needs the plain executable, not an archive) between the build and the pack step.
fn dist(args: Vec<String>) -> Result<ExitCode, String> {
    let mut no_build = false;
    for arg in args {
        match arg.as_str() {
            "--no-build" => no_build = true,
            other => return Err(format!("dist: unknown argument {other}")),
        }
    }
    if !no_build {
        run_cargo(&["build", "--release", "--locked", "--package", "tachyon"])?;
    }
    let root = workspace_root();
    let version = workspace_version(&root)?;
    let name = format!("tachyon-{version}-{}-{}", std::env::consts::ARCH, std::env::consts::OS);
    let dist = release_binary()
        .parent()
        .and_then(|release| release.parent())
        .ok_or("no target directory")?
        .join("dist");
    let stage = dist.join(&name);
    let _ = std::fs::remove_dir_all(&stage);
    std::fs::create_dir_all(&stage).map_err(|e| format!("{}: {e}", stage.display()))?;
    let binary = release_binary();
    let copy = |from: &std::path::Path| -> Result<(), String> {
        let to = stage.join(from.file_name().ok_or("file without a name")?);
        std::fs::copy(from, &to).map(drop).map_err(|e| format!("{}: {e}", from.display()))
    };
    copy(&binary)?;
    for file in DIST_FILES {
        copy(&root.join(file))?;
    }
    // Windows 10 and later ship bsdtar, which writes zip archives (`-a` picks the format from the
    // extension); elsewhere a gzipped tar is the norm.
    let archive = if cfg!(windows) { format!("{name}.zip") } else { format!("{name}.tar.gz") };
    let mut tar = Command::new("tar");
    if cfg!(windows) {
        tar.args(["-a", "-c", "-f", &archive, &name]);
    } else {
        tar.args(["-c", "-z", "-f", &archive, &name]);
    }
    let status = tar.current_dir(&dist).status().map_err(|e| format!("failed to run tar: {e}"))?;
    if !status.success() {
        return Err("tar failed".into());
    }
    let path = dist.join(&archive);
    let size = std::fs::metadata(&path).map_err(|e| format!("{}: {e}", path.display()))?.len();
    println!("{} ({:.1} MB)", path.display(), size as f64 / 1e6);
    Ok(ExitCode::SUCCESS)
}

/// Icon sizes and the art drawn at each. Up to 32 px (the tray, title bar and taskbar at 100 %)
/// the full mark's orbit arcs read as a digit, so those sizes use a dedicated few-stroke arrow
/// (`app-icon-16.svg`); 40 px and up show the full mark.
const ICON_SIZES: [(u32, &str); 7] = [
    (16, "app-icon-16.svg"),
    (20, "app-icon-16.svg"),
    (24, "app-icon-16.svg"),
    (32, "app-icon-16.svg"),
    (40, "app-icon.svg"),
    (48, "app-icon.svg"),
    (64, "app-icon.svg"),
];

/// Sizes rendered into `packaging/msix/Assets` for the MSIX manifest's `Square44x44Logo` slot,
/// plus the tile and store logos. Same art selection as `ICON_SIZES` (`app-icon-16.svg` up to
/// 32 px, `app-icon.svg` above). Windows discovers the `targetsize-<n>` and
/// `_altform-unplated`-qualified siblings of the file the manifest names by filename convention
/// alone, so nothing else in the manifest changes when these are added; Tachyon's art is
/// transparent throughout (`BackgroundColor="transparent"` in the manifest), so the "plated" and
/// "unplated" forms are the same image.
const MSIX_ASSETS: [(&str, u32, &str); 13] = [
    ("Square44x44Logo.png", 44, "app-icon.svg"),
    ("Square44x44Logo.targetsize-16.png", 16, "app-icon-16.svg"),
    ("Square44x44Logo.targetsize-16_altform-unplated.png", 16, "app-icon-16.svg"),
    ("Square44x44Logo.targetsize-24.png", 24, "app-icon-16.svg"),
    ("Square44x44Logo.targetsize-24_altform-unplated.png", 24, "app-icon-16.svg"),
    ("Square44x44Logo.targetsize-32.png", 32, "app-icon-16.svg"),
    ("Square44x44Logo.targetsize-32_altform-unplated.png", 32, "app-icon-16.svg"),
    ("Square44x44Logo.targetsize-48.png", 48, "app-icon.svg"),
    ("Square44x44Logo.targetsize-48_altform-unplated.png", 48, "app-icon.svg"),
    ("Square44x44Logo.targetsize-256.png", 256, "app-icon.svg"),
    ("Square44x44Logo.targetsize-256_altform-unplated.png", 256, "app-icon.svg"),
    ("Square150x150Logo.png", 150, "app-icon.svg"),
    ("StoreLogo.png", 50, "app-icon.svg"),
];

/// Runs an external tool `cargo xtask icons` needs, turning a missing program into a message that
/// names it instead of a bare "No such file or directory".
fn run_tool(program: &str, args: &[&std::ffi::OsStr]) -> Result<(), String> {
    let status = Command::new(program)
        .args(args)
        .status()
        .map_err(|e| format!("{program} is needed for `cargo xtask icons` ({e})"))?;
    if status.success() { Ok(()) } else { Err(format!("{program} failed")) }
}

/// Rasterizes `art` (an SVG in `assets/brand`) to a `size` x `size` PNG at `dest`.
fn render_svg(
    brand: &std::path::Path,
    art: &str,
    size: u32,
    dest: &std::path::Path,
) -> Result<(), String> {
    let size = size.to_string();
    run_tool(
        "rsvg-convert",
        &[
            "-w".as_ref(),
            size.as_ref(),
            "-h".as_ref(),
            size.as_ref(),
            brand.join(art).as_os_str(),
            "-o".as_ref(),
            dest.as_os_str(),
        ],
    )
}

/// `cargo xtask icons`: rasterizes the brand SVGs into the `.ico` the tray, the windows and the
/// executable embed, the MSIX assets `packaging/msix/AppxManifest.xml` names, and copies the
/// launcher SVG. The `.ico` sizes stay at 64 px and below, which ImageMagick writes as DIB
/// images: the tray creates icons without an image codec and rejects PNG entries.
fn icons() -> Result<ExitCode, String> {
    let root = workspace_root();
    let brand = root.join("assets/brand");
    let out = root.join("crates/tachyon-platform/assets");
    let msix_assets = root.join("packaging/msix/Assets");
    let work = std::env::temp_dir().join(format!("tachyon-icons-{}", std::process::id()));
    std::fs::create_dir_all(&work).map_err(|e| e.to_string())?;

    let mut pngs = Vec::new();
    for (size, art) in ICON_SIZES {
        let png = work.join(format!("{size}.png"));
        render_svg(&brand, art, size, &png)?;
        pngs.push(png);
    }
    // Written and checked in the scratch directory first, so a bad ICO never replaces the tracked
    // one that builds embed.
    let staged_ico = work.join("tachyon.ico");
    let mut ico_args: Vec<&std::ffi::OsStr> = pngs.iter().map(|p| p.as_os_str()).collect();
    ico_args.push(staged_ico.as_os_str());
    let ico_result = run_tool("magick", &ico_args)
        .and_then(|()| std::fs::read(&staged_ico).map_err(|e| e.to_string()))
        .and_then(|bytes| check_dib_icon(&bytes))
        .and_then(|()| {
            let ico = out.join("tachyon.ico");
            std::fs::copy(&staged_ico, &ico)
                .map(drop)
                .map_err(|e| format!("{}: {e}", ico.display()))
        });

    // Rendered and copied only if every asset renders, so a partial failure never leaves a stale
    // asset next to fresh ones.
    let msix_result = (|| -> Result<(), String> {
        let mut staged = Vec::new();
        for (name, size, art) in MSIX_ASSETS {
            let dest = work.join(name);
            render_svg(&brand, art, size, &dest)?;
            staged.push((dest, name));
        }
        std::fs::create_dir_all(&msix_assets)
            .map_err(|e| format!("{}: {e}", msix_assets.display()))?;
        for (dest, name) in staged {
            let target = msix_assets.join(name);
            std::fs::copy(&dest, &target)
                .map(drop)
                .map_err(|e| format!("{}: {e}", target.display()))?;
        }
        Ok(())
    })();

    let svg = out.join("tachyon.svg");
    let svg_result = std::fs::copy(brand.join("app-icon.svg"), &svg)
        .map(drop)
        .map_err(|e| format!("{}: {e}", svg.display()));

    let _ = std::fs::remove_dir_all(&work);
    ico_result?;
    msix_result?;
    svg_result?;
    println!(
        "{}, {} MSIX assets in {} and {} updated",
        out.join("tachyon.ico").display(),
        MSIX_ASSETS.len(),
        msix_assets.display(),
        svg.display()
    );
    Ok(ExitCode::SUCCESS)
}

/// Every image in the `.ico` is a 32-bit DIB (a `BITMAPINFOHEADER` with 32 bits per pixel, not a
/// PNG).
fn check_dib_icon(ico: &[u8]) -> Result<(), String> {
    let u16_at = |at: usize| ico.get(at..at + 2).map(|b| u16::from_le_bytes([b[0], b[1]]));
    let count = u16_at(4).ok_or("the icon file is truncated")?;
    for i in 0..usize::from(count) {
        let offset = ico
            .get(18 + 16 * i..22 + 16 * i)
            .map(|b| u32::from_le_bytes([b[0], b[1], b[2], b[3]]) as usize)
            .ok_or("the icon directory is truncated")?;
        let header = ico.get(offset..offset + 4) == Some(&[40, 0, 0, 0][..]);
        if !header || u16_at(offset + 14) != Some(32) {
            return Err(format!("icon image {i} is not a 32-bit DIB"));
        }
    }
    Ok(())
}

/// `version` from the workspace manifest's `[workspace.package]` table.
fn workspace_version(root: &std::path::Path) -> Result<String, String> {
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).map_err(|e| e.to_string())?;
    manifest
        .split("[workspace.package]")
        .nth(1)
        .and_then(|table| table.lines().find_map(|line| line.trim().strip_prefix("version = ")))
        .map(|version| version.trim_matches('"').to_owned())
        .ok_or_else(|| "no version in [workspace.package]".into())
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask is inside the workspace")
        .into()
}

fn release_binary() -> PathBuf {
    let target_dir = std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| workspace_root().join("target"));
    target_dir.join("release").join(format!("tachyon{}", std::env::consts::EXE_SUFFIX))
}

/// Converts a 3-part workspace version ("0.1.0") to the 4-part quad the MSIX manifest and
/// `.appinstaller` require ("0.1.0.0"), or validates that a 4-part override already is one.
fn to_version4(version: &str) -> Result<String, String> {
    let parts: Vec<&str> = version.split('.').collect();
    let numeric = parts.iter().all(|p| !p.is_empty() && p.bytes().all(|b| b.is_ascii_digit()));
    match parts.len() {
        3 if numeric => Ok(format!("{version}.0")),
        4 if numeric => Ok(version.to_owned()),
        _ => Err(format!("version must be 3 or 4 dot-separated numbers, got {version:?}")),
    }
}

/// Reads `Name` and `Publisher` out of the manifest template's `<Identity>` element, so
/// `Tachyon.appinstaller` never states them separately from `packaging/msix/AppxManifest.xml`
/// (Publisher must match the Azure Trusted Signing certificate subject exactly, or the MSIX
/// will not install).
fn manifest_identity(manifest: &str) -> Result<(String, String), String> {
    let start = manifest.find("<Identity").ok_or("AppxManifest.xml: no <Identity> element")?;
    let end = manifest[start..]
        .find("/>")
        .map(|i| start + i)
        .ok_or("AppxManifest.xml: <Identity> is not self-closing")?;
    let identity = &manifest[start..end];
    let attr = |name: &str| -> Result<String, String> {
        let needle = format!("{name}=\"");
        let at = identity
            .find(&needle)
            .ok_or_else(|| format!("AppxManifest.xml: <Identity> has no {name}"))?
            + needle.len();
        let rest = &identity[at..];
        let close =
            rest.find('"').ok_or_else(|| format!("AppxManifest.xml: {name} is not closed"))?;
        Ok(rest[..close].to_owned())
    };
    Ok((attr("Name")?, attr("Publisher")?))
}

/// Highest-versioned `makeappx.exe` under the Windows 10/11 SDK's `bin` directory. Its version
/// folders are all `10.0.<5-digit build>.0`, so a plain string sort of the directory names picks
/// the newest build.
fn find_makeappx() -> Result<PathBuf, String> {
    let sdk_bin = PathBuf::from(r"C:\Program Files (x86)\Windows Kits\10\bin");
    let mut versions: Vec<PathBuf> = std::fs::read_dir(&sdk_bin)
        .map_err(|e| format!("{}: {e} (install the Windows 10/11 SDK)", sdk_bin.display()))?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    versions.sort();
    versions
        .into_iter()
        .rev()
        .map(|dir| dir.join("x64").join("makeappx.exe"))
        .find(|candidate| candidate.is_file())
        .ok_or_else(|| {
            format!("no makeappx.exe under {} (install the Windows 10/11 SDK)", sdk_bin.display())
        })
}

/// `cargo xtask msix`: packs the signed `target/release/tachyon.exe`, `packaging/msix/Assets`
/// and the manifest (with its version filled in) into an MSIX with `makeappx.exe`, then writes
/// the `.appinstaller` that points App Installer at it for auto-update.
fn msix(args: Vec<String>) -> Result<ExitCode, String> {
    if !cfg!(windows) {
        return Err(
            "msix is only supported on Windows (it packs with makeappx.exe from the Windows \
             10/11 SDK)"
                .into(),
        );
    }
    let mut version_override = None;
    let mut appinstaller_base = None;
    let mut args = args.into_iter();
    while let Some(arg) = args.next() {
        let mut value = || args.next().ok_or_else(|| format!("{arg} needs a value"));
        match arg.as_str() {
            "--version" => version_override = Some(value()?),
            "--appinstaller-base" => appinstaller_base = Some(value()?),
            _ => return Err(format!("unknown argument {arg}\n\n{USAGE}")),
        }
    }

    let root = workspace_root();
    let version = match &version_override {
        Some(v) => to_version4(v)?,
        None => to_version4(&workspace_version(&root)?)?,
    };
    // The GitHub release tag is the version's first three parts (`v0.1.0`), even when
    // `--version` overrides the fourth part for update testing; pair that with
    // `--appinstaller-base` when the tag does not really carry this build.
    let version3 = version.rsplit_once('.').map_or(version.as_str(), |(head, _)| head);

    let exe = release_binary();
    if !exe.is_file() {
        return Err(format!(
            "{}: build and sign the release binary first (cargo build --release -p tachyon)",
            exe.display()
        ));
    }
    let dist = exe
        .parent()
        .and_then(|release| release.parent())
        .ok_or("no target directory")?
        .join("dist");
    std::fs::create_dir_all(&dist).map_err(|e| format!("{}: {e}", dist.display()))?;

    let stage = dist.join("msix-stage");
    let _ = std::fs::remove_dir_all(&stage);
    let stage_assets = stage.join("Assets");
    std::fs::create_dir_all(&stage_assets)
        .map_err(|e| format!("{}: {e}", stage_assets.display()))?;

    let manifest_path = root.join("packaging/msix/AppxManifest.xml");
    let manifest_template = std::fs::read_to_string(&manifest_path)
        .map_err(|e| format!("{}: {e}", manifest_path.display()))?;
    let (name, publisher) = manifest_identity(&manifest_template)?;
    let manifest = manifest_template.replace("{{VERSION}}", &version);
    let staged_manifest = stage.join("AppxManifest.xml");
    std::fs::write(&staged_manifest, manifest)
        .map_err(|e| format!("{}: {e}", staged_manifest.display()))?;

    std::fs::copy(&exe, stage.join("tachyon.exe"))
        .map(drop)
        .map_err(|e| format!("{}: {e}", exe.display()))?;

    let assets_src = root.join("packaging/msix/Assets");
    for entry in
        std::fs::read_dir(&assets_src).map_err(|e| format!("{}: {e}", assets_src.display()))?
    {
        let entry = entry.map_err(|e| e.to_string())?;
        let dest = stage_assets.join(entry.file_name());
        std::fs::copy(entry.path(), &dest)
            .map(drop)
            .map_err(|e| format!("{}: {e}", dest.display()))?;
    }

    let makeappx = find_makeappx()?;
    let package_name = format!("Tachyon_{version}_x64.msix");
    let package_path = dist.join(&package_name);
    let status = Command::new(&makeappx)
        .arg("pack")
        .arg("/o")
        .arg("/d")
        .arg(&stage)
        .arg("/p")
        .arg(&package_path)
        .status()
        .map_err(|e| format!("{}: {e}", makeappx.display()))?;
    let _ = std::fs::remove_dir_all(&stage);
    if !status.success() {
        return Err("makeappx pack failed".into());
    }

    let (self_uri, package_uri) = match &appinstaller_base {
        Some(base) => {
            let base = base.trim_end_matches('/');
            (format!("{base}/Tachyon.appinstaller"), format!("{base}/{package_name}"))
        }
        None => (
            "https://github.com/DailenG/tachyon/releases/latest/download/Tachyon.appinstaller"
                .to_owned(),
            format!(
                "https://github.com/DailenG/tachyon/releases/download/v{version3}/{package_name}"
            ),
        ),
    };
    let appinstaller = format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <AppInstaller\n    \
             xmlns=\"http://schemas.microsoft.com/appx/appinstaller/2021\"\n    \
             Version=\"{version}\"\n    \
             Uri=\"{self_uri}\">\n\n  \
           <MainPackage\n      \
               Name=\"{name}\"\n      \
               Publisher=\"{publisher}\"\n      \
               Version=\"{version}\"\n      \
               ProcessorArchitecture=\"x64\"\n      \
               Uri=\"{package_uri}\" />\n\n  \
           <UpdateSettings>\n    \
             <OnLaunch HoursBetweenUpdateChecks=\"0\" ShowPrompt=\"false\" \
             UpdateBlocksActivation=\"false\" />\n    \
             <AutomaticBackgroundTask />\n  \
           </UpdateSettings>\n\n\
         </AppInstaller>\n"
    );
    let appinstaller_path = dist.join("Tachyon.appinstaller");
    std::fs::write(&appinstaller_path, appinstaller)
        .map_err(|e| format!("{}: {e}", appinstaller_path.display()))?;

    let size_mb = |path: &std::path::Path| -> f64 {
        std::fs::metadata(path).map(|m| m.len() as f64 / 1e6).unwrap_or(0.0)
    };
    println!("{} ({:.1} MB)", package_path.display(), size_mb(&package_path));
    println!("{}", appinstaller_path.display());
    Ok(ExitCode::SUCCESS)
}

/// One launch: wall time from `spawn` to the report line, plus the in-process
/// milestones the binary printed.
struct Sample {
    external: Duration,
    marks: BTreeMap<String, Duration>,
}

fn bench_startup(args: Vec<String>) -> Result<ExitCode, String> {
    let options = parse_bench_options(args)?;
    if options.build && options.bin.is_none() {
        run_cargo(&["build", "--release", "--package", "tachyon"])?;
    }
    let bin = options.bin.clone().unwrap_or_else(release_binary);

    if options.warm {
        let samples = bench_warm(&bin, options.runs, options.gap)?;
        return Ok(report(&samples, options.budget, "receipt"));
    }
    let mut samples = Vec::with_capacity(options.runs);
    for run in 1..=options.runs {
        let sample = launch_once(&bin).map_err(|e| format!("run {run}: {e}"))?;
        samples.push(sample);
    }
    Ok(report(&samples, options.budget, "main"))
}

/// Starts a resident instance (on a private instance id, so a running
/// Tachyon is not involved), then times launches handed to it.
fn bench_warm(bin: &PathBuf, runs: usize, gap: Duration) -> Result<Vec<Sample>, String> {
    let id = format!("tachyon-bench-{}", std::process::id());
    let mut resident = Command::new(bin)
        .arg("--report-launches")
        .env("TACHYON_INSTANCE_ID", &id)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| format!("failed to launch {}: {e}", bin.display()))?;
    let stdout = resident.stdout.take().expect("stdout is piped");
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        for line in BufReader::new(stdout).lines().map_while(Result::ok) {
            if tx.send((Instant::now(), line)).is_err() {
                break;
            }
        }
    });

    let result = (|| {
        wait_for_line(&rx, "tachyon-ready")?;
        let mut samples = Vec::with_capacity(runs);
        for run in 1..=runs {
            std::thread::sleep(gap);
            let started = Instant::now();
            let status = Command::new(bin)
                .env("TACHYON_INSTANCE_ID", &id)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .status()
                .map_err(|e| format!("run {run}: failed to launch: {e}"))?;
            if !status.success() {
                return Err(format!("run {run}: launch exited with {status}"));
            }
            let (at, line) =
                wait_for_line(&rx, "tachyon-launch").map_err(|e| format!("run {run}: {e}"))?;
            samples.push(Sample { external: at - started, marks: parse_report(&line)? });
        }
        Ok(samples)
    })();
    let _ = resident.kill();
    let _ = resident.wait();
    result
}

fn wait_for_line(
    rx: &mpsc::Receiver<(Instant, String)>,
    prefix: &str,
) -> Result<(Instant, String), String> {
    let deadline = Instant::now() + RUN_TIMEOUT;
    loop {
        let left = deadline.saturating_duration_since(Instant::now());
        match rx.recv_timeout(left) {
            Ok((at, line)) if line.starts_with(prefix) => return Ok((at, line)),
            Ok(_) => continue,
            Err(_) => return Err(format!("resident instance did not print `{prefix}`")),
        }
    }
}

fn launch_once(bin: &PathBuf) -> Result<Sample, String> {
    let started = Instant::now();
    let mut child = Command::new(bin)
        .arg("--startup-report")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| format!("failed to launch {}: {e}", bin.display()))?;

    let stdout = child.stdout.take().expect("stdout is piped");
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        for line in BufReader::new(stdout).lines() {
            let Ok(line) = line else { break };
            if line.starts_with(REPORT_PREFIX) {
                let _ = tx.send((Instant::now(), line));
                break;
            }
        }
    });

    let received = rx.recv_timeout(RUN_TIMEOUT);
    let exited = wait_with_timeout(&mut child, RUN_TIMEOUT);
    let (at, line) = received
        .map_err(|_| "no startup report received (did the window fail to open?)".to_owned())?;
    if !exited {
        return Err("tachyon did not exit after reporting".into());
    }
    Ok(Sample { external: at - started, marks: parse_report(&line)? })
}

fn wait_with_timeout(child: &mut std::process::Child, timeout: Duration) -> bool {
    let deadline = Instant::now() + timeout;
    loop {
        match child.try_wait() {
            Ok(Some(_)) => return true,
            Ok(None) if Instant::now() < deadline => std::thread::sleep(Duration::from_millis(5)),
            _ => {
                let _ = child.kill();
                let _ = child.wait();
                return false;
            }
        }
    }
}

fn parse_report(line: &str) -> Result<BTreeMap<String, Duration>, String> {
    line.split_whitespace()
        .skip(1)
        .map(|field| {
            let (key, value) = field.split_once('=').ok_or_else(|| format!("bad field {field}"))?;
            let name = key.strip_suffix("_us").ok_or_else(|| format!("bad field {field}"))?;
            let us: u64 = value.parse().map_err(|e| format!("bad field {field}: {e}"))?;
            Ok((name.to_owned(), Duration::from_micros(us)))
        })
        .collect()
}

/// Nearest-rank percentile of a non-empty, sorted slice.
fn percentile(sorted: &[Duration], p: f64) -> Duration {
    let rank = ((p * sorted.len() as f64).ceil() as usize).clamp(1, sorted.len());
    sorted[rank - 1]
}

/// `marks_from` names where the in-process milestones are measured from.
fn report(samples: &[Sample], budget: Duration, marks_from: &str) -> ExitCode {
    let ms = |d: Duration| format!("{:>8.2}", d.as_secs_f64() * 1000.0);
    let mut rows: Vec<(String, Vec<Duration>)> =
        vec![("spawn -> first frame".into(), samples.iter().map(|s| s.external).collect())];
    for name in samples[0].marks.keys() {
        let values = samples.iter().filter_map(|s| s.marks.get(name).copied()).collect();
        rows.push((format!("{marks_from} -> {name}"), values));
    }

    // The first launch has the coldest caches: it gets its own column, and
    // the percentiles (and the verdict) cover the remaining runs.
    let warm = samples.len() > 1;
    let rest_of = |values: &[Duration]| {
        let mut rest = if warm { values[1..].to_vec() } else { values.to_vec() };
        rest.sort();
        rest
    };
    println!(
        "{:<24}{:>9}{:>9}{:>9}{:>9}   ({} runs, ms)",
        "metric",
        "first",
        "p50",
        "p95",
        "max",
        samples.len()
    );
    for (name, values) in &rows {
        let first = values[0];
        let rest = rest_of(values);
        println!(
            "{name:<24} {} {} {} {}",
            ms(first),
            ms(percentile(&rest, 0.50)),
            ms(percentile(&rest, 0.95)),
            ms(*rest.last().expect("non-empty"))
        );
    }

    // Same statistic as the table's p95 column for the first row.
    let p95 = percentile(&rest_of(&rows[0].1), 0.95);
    let verdict = if p95 <= budget { "PASS" } else { "FAIL" };
    let runs = if warm { format!("runs 2-{}", samples.len()) } else { "1 run".to_owned() };
    println!(
        "\n{verdict}: p95 spawn -> first frame {:.2} ms (budget {} ms, {runs})",
        p95.as_secs_f64() * 1000.0,
        budget.as_millis()
    );
    if p95 <= budget { ExitCode::SUCCESS } else { ExitCode::FAILURE }
}
