//! Development tasks. Run with `cargo xtask <task>`.

use std::collections::BTreeMap;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};
use std::sync::mpsc;
use std::time::{Duration, Instant};

const USAGE: &str = "\
Usage: cargo xtask <TASK>

Tasks:
  ci
      Runs the checks required by CI: rustfmt, clippy, tests and cargo-deny
      (when installed). Run before pushing.
  bench-startup [--warm [--gap-ms MS]] [--runs N] [--budget-ms MS] [--bin PATH] [--no-build]
      Launches the release binary N times (default 20) with --startup-report and
      reports spawn-to-first-frame latency. The first run is reported on its
      own (coldest caches); percentiles cover the other runs. Exits non-zero
      if their p95 exceeds the budget (default 50 ms).
      --warm measures launches handed to a resident instance instead: spawn of
      the second process until the resident instance has drawn the new window.
      --gap-ms waits between those launches (default 500, like a person; the
      resident instance prepares its next window in between).
  dist [--no-build]
      Builds the release binary and packs it with the README, changelog and
      licenses into target/dist/tachyon-<version>-<arch>-<os>.zip on Windows,
      .tar.gz elsewhere. --no-build skips the build and packs the binary
      already at target/release (used after signing it in place).
  icons
      Regenerates the application's icons from assets/brand: tachyon.ico (16-128 px
      as 32-bit DIB images, plus one 256 px PNG) and the launcher SVG, both in
      crates/tachyon-platform/assets, and the MSIX PNGs in packaging/msix/Assets.
      Needs rsvg-convert and ImageMagick (magick).
      Run after changing the brand art; the build only embeds the results.
  msix [--version X.Y.Z.W] [--appinstaller-base URL-OR-PATH]
      Windows only (needs makeappx.exe from the Windows 10/11 SDK). Packs
      target/release/tachyon.exe and packaging/msix/Assets (regenerated by
      `cargo xtask icons`) into target/dist/Tachyon_<version>_x64.msix, and
      writes target/dist/Tachyon.appinstaller for App Installer auto-update.
      --version overrides the manifest's 4-part version (workspace version
      + \".0\" by default; use a bumped 4th part to test that App Installer
      offers an update). --appinstaller-base overrides where the
      .appinstaller points (default the GitHub release URLs), for testing
      updates from another location.
";

const REPORT_PREFIX: &str = "tachyon-startup";
const RUN_TIMEOUT: Duration = Duration::from_secs(15);

fn main() -> ExitCode {
    let mut args = std::env::args().skip(1);
    let result = match args.next().as_deref() {
        Some("ci") => ci(args.collect()),
        Some("bench-startup") => bench_startup(args.collect()),
        Some("dist") => dist(args.collect()),
        Some("icons") => icons(),
        Some("msix") => msix(args.collect()),
        _ => {
            eprint!("{USAGE}");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(code) => code,
        Err(e) => {
            eprintln!("xtask: {e}");
            ExitCode::FAILURE
        }
    }
}

fn cargo() -> Command {
    let mut command = Command::new(std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into()));
    command.current_dir(workspace_root());
    command
}

fn run_cargo(args: &[&str]) -> Result<(), String> {
    let line = format!("cargo {}", args.join(" "));
    eprintln!("$ {line}");
    let status = cargo().args(args).status().map_err(|e| format!("failed to run {line}: {e}"))?;
    if status.success() { Ok(()) } else { Err(format!("`{line}` failed")) }
}

/// Mirrors the required CI jobs so a green local run predicts a green PR.
fn ci(args: Vec<String>) -> Result<ExitCode, String> {
    if let Some(arg) = args.first() {
        return Err(format!("ci takes no arguments, got {arg}"));
    }
    run_cargo(&["fmt", "--all", "--check"])?;
    run_cargo(&["clippy", "--workspace", "--all-targets", "--locked", "--", "-D", "warnings"])?;
    run_cargo(&["test", "--workspace", "--locked"])?;
    if Command::new("cargo-deny").arg("--version").output().is_ok() {
        run_cargo(&["deny", "check"])?;
    } else {
        eprintln!(
            "xtask: cargo-deny is not installed; `cargo deny check` skipped (CI enforces it).\n\
             Install with: cargo install cargo-deny --locked"
        );
    }
    Ok(ExitCode::SUCCESS)
}

struct BenchOptions {
    runs: usize,
    budget: Duration,
    bin: Option<PathBuf>,
    build: bool,
    warm: bool,
    gap: Duration,
}

fn parse_bench_options(args: Vec<String>) -> Result<BenchOptions, String> {
    let mut options = BenchOptions {
        runs: 20,
        budget: Duration::from_millis(50),
        bin: None,
        build: true,
        warm: false,
        gap: Duration::from_millis(500),
    };
    let mut args = args.into_iter();
    while let Some(arg) = args.next() {
        let mut value = || args.next().ok_or_else(|| format!("{arg} needs a value"));
        match arg.as_str() {
            "--runs" => {
                options.runs = value()?.parse().map_err(|e| format!("--runs: {e}"))?;
                if options.runs == 0 {
                    return Err("--runs must be at least 1".into());
                }
            }
            "--budget-ms" => {
                let ms: u64 = value()?.parse().map_err(|e| format!("--budget-ms: {e}"))?;
                options.budget = Duration::from_millis(ms);
            }
            "--bin" => options.bin = Some(value()?.into()),
            "--no-build" => options.build = false,
            "--warm" => options.warm = true,
            "--gap-ms" => {
                let ms: u64 = value()?.parse().map_err(|e| format!("--gap-ms: {e}"))?;
                options.gap = Duration::from_millis(ms);
            }
            _ => return Err(format!("unknown argument {arg}\n\n{USAGE}")),
        }
    }
    Ok(options)
}

/// Files shipped next to the binary in a release archive.
const DIST_FILES: [&str; 4] = ["README.md", "CHANGELOG.md", "LICENSE-MIT", "LICENSE-APACHE"];

/// `--no-build` packs whatever is already at `target/release`, so CI can sign the binary (Windows
/// code signing needs the plain executable, not an archive) between the build and the pack step.
fn dist(args: Vec<String>) -> Result<ExitCode, String> {
    let mut no_build = false;
    for arg in args {
        match arg.as_str() {
            "--no-build" => no_build = true,
            other => return Err(format!("dist: unknown argument {other}")),
        }
    }
    if !no_build {
        run_cargo(&["build", "--release", "--locked", "--package", "tachyon"])?;
    }
    let root = workspace_root();
    let version = workspace_version(&root)?;
    let name = format!("tachyon-{version}-{}-{}", std::env::consts::ARCH, std::env::consts::OS);
    let dist = release_binary()
        .parent()
        .and_then(|release| release.parent())
        .ok_or("no target directory")?
        .join("dist");
    let stage = dist.join(&name);
    let _ = std::fs::remove_dir_all(&stage);
    std::fs::create_dir_all(&stage).map_err(|e| format!("{}: {e}", stage.display()))?;
    let binary = release_binary();
    let copy = |from: &Path| -> Result<(), String> {
        let to = stage.join(from.file_name().ok_or("file without a name")?);
        std::fs::copy(from, &to).map(drop).map_err(|e| format!("{}: {e}", from.display()))
    };
    copy(&binary)?;
    for file in DIST_FILES {
        copy(&root.join(file))?;
    }
    // Windows 10 and later ship bsdtar, which writes zip archives (`-a` picks the format from the
    // extension); elsewhere a gzipped tar is the norm.
    let archive = if cfg!(windows) { format!("{name}.zip") } else { format!("{name}.tar.gz") };
    let mut tar = Command::new("tar");
    if cfg!(windows) {
        tar.args(["-a", "-c", "-f", &archive, &name]);
    } else {
        tar.args(["-c", "-z", "-f", &archive, &name]);
    }
    let status = tar.current_dir(&dist).status().map_err(|e| format!("failed to run tar: {e}"))?;
    if !status.success() {
        return Err("tar failed".into());
    }
    let path = dist.join(&archive);
    let size = std::fs::metadata(&path).map_err(|e| format!("{}: {e}", path.display()))?.len();
    println!("{} ({:.1} MB)", path.display(), size as f64 / 1e6);
    Ok(ExitCode::SUCCESS)
}

/// The app icon art in `assets/brand`, each drawn on its own pixel grid by
/// `scripts/brand/compose.py`: (grid size in px, file). A raster of any size is rendered from the
/// smallest art at least that large ([`icon_art`]), so every size gets art meant for it or for
/// a size just above it, never art stretched up. 16-32 px is the simplified mark with a solid
/// border; 40 px and up the full mark with a gradient border.
const ICON_ART: [(u32, &str); 8] = [
    (16, "app-icon-16.svg"),
    (20, "app-icon-20.svg"),
    (24, "app-icon-24.svg"),
    (32, "app-icon-32.svg"),
    (40, "app-icon-40.svg"),
    (48, "app-icon-48.svg"),
    (64, "app-icon-64.svg"),
    (256, "app-icon.svg"),
];

/// The art for a `size` px raster: the smallest grid at least that large, else the largest.
fn icon_art(size: u32) -> &'static str {
    ICON_ART.iter().find(|(grid, _)| *grid >= size).unwrap_or(&ICON_ART[ICON_ART.len() - 1]).1
}

/// File-type icon art in `assets/brand` (`scripts/brand/compose.py`, `file_icons`): the grids each
/// kind is drawn on, and the kinds as (MSIX asset name, art name).
const FILE_ART_GRIDS: [u32; 5] = [16, 24, 32, 48, 256];
const FILE_KINDS: [(&str, &str); 2] = [("FileMarkdown", "markdown"), ("FileText", "text")];

/// Sizes rendered per file kind into `packaging/msix/Assets`, as the manifest's `<uap:Logo>` for
/// each `FileTypeAssociation` and its `targetsize-<n>` siblings, which Explorer picks by size.
/// `None` is the unqualified file the manifest names.
const FILE_SIZES: [(Option<u32>, u32); 6] =
    [(None, 48), (Some(16), 16), (Some(24), 24), (Some(32), 32), (Some(48), 48), (Some(256), 256)];

/// The file-type art of `kind` for a `size` px raster: the smallest grid at least that large.
fn file_art(kind: &str, size: u32) -> String {
    let grid = FILE_ART_GRIDS.iter().copied().find(|&g| g >= size).unwrap_or(256);
    format!("file-{kind}-{grid}.svg")
}

/// Sizes in `tachyon.ico`, all 32-bit DIB images: 16-32 px for the tray, title bar and taskbar
/// at 100-200 % scaling; 40-64 px for Alt+Tab and the taskbar at higher scaling; 96 and 128 px for
/// the large window icon at 300 and 400 % (`SM_CXICON`). The tray creates its icons with
/// `CreateIconFromResourceEx` from these DIBs (see `crates/tachyon-platform/src/windows/tray.rs`).
const ICO_DIB_SIZES: [u32; 9] = [16, 20, 24, 32, 40, 48, 64, 96, 128];

/// The one PNG-compressed image in `tachyon.ico`, last in the file: 256 px for Explorer's large
/// and extra-large views, the Start menu and Alt+Tab at high scaling. Explorer reads PNG entries;
/// the tray never uses this one (`ico_image` skips PNG entries). As a DIB it would be 270 KB, and
/// the executable holds the `.ico` twice (its icon resource and the tray's `include_bytes!`); as
/// a PNG it is about 31 KB.
const ICO_PNG_SIZE: u32 = 256;

/// Sizes rendered into `packaging/msix/Assets` for the MSIX manifest's `Square44x44Logo` slot,
/// plus the tile and store logos, each from [`icon_art`]. Windows discovers the `targetsize-<n>`
/// and `_altform-unplated`-qualified siblings of the file the manifest names by filename
/// convention alone, so nothing else in the manifest changes when these are added; Tachyon's art
/// is transparent outside its tile (`BackgroundColor="transparent"` in the manifest), so the
/// "plated" and "unplated" forms are the same image.
const MSIX_ASSETS: [(&str, u32); 13] = [
    ("Square44x44Logo.png", 44),
    ("Square44x44Logo.targetsize-16.png", 16),
    ("Square44x44Logo.targetsize-16_altform-unplated.png", 16),
    ("Square44x44Logo.targetsize-24.png", 24),
    ("Square44x44Logo.targetsize-24_altform-unplated.png", 24),
    ("Square44x44Logo.targetsize-32.png", 32),
    ("Square44x44Logo.targetsize-32_altform-unplated.png", 32),
    ("Square44x44Logo.targetsize-48.png", 48),
    ("Square44x44Logo.targetsize-48_altform-unplated.png", 48),
    ("Square44x44Logo.targetsize-256.png", 256),
    ("Square44x44Logo.targetsize-256_altform-unplated.png", 256),
    ("Square150x150Logo.png", 150),
    ("StoreLogo.png", 50),
];

/// Runs an external tool `cargo xtask icons` needs, turning a missing program into a message that
/// names it instead of a bare "No such file or directory".
fn run_tool(program: &str, args: &[&std::ffi::OsStr]) -> Result<(), String> {
    let status = Command::new(program)
        .args(args)
        .status()
        .map_err(|e| format!("{program} is needed for `cargo xtask icons` ({e})"))?;
    if status.success() { Ok(()) } else { Err(format!("{program} failed")) }
}

/// Rasterizes `art` (an SVG in `assets/brand`) to a `size` x `size` PNG at `dest`.
fn render_svg(brand: &Path, art: &str, size: u32, dest: &Path) -> Result<(), String> {
    let size = size.to_string();
    run_tool(
        "rsvg-convert",
        &[
            "-w".as_ref(),
            size.as_ref(),
            "-h".as_ref(),
            size.as_ref(),
            brand.join(art).as_os_str(),
            "-o".as_ref(),
            dest.as_os_str(),
        ],
    )
}

/// `cargo xtask icons`: rasterizes the brand SVGs into the `.ico` the tray, the windows and the
/// executable embed, the MSIX assets `packaging/msix/AppxManifest.xml` names, and copies the
/// launcher SVG.
fn icons() -> Result<ExitCode, String> {
    let root = workspace_root();
    let brand = root.join("assets/brand");
    let out = root.join("crates/tachyon-platform/assets");
    let msix_assets = root.join("packaging/msix/Assets");
    let work = std::env::temp_dir().join(format!("tachyon-icons-{}", std::process::id()));
    std::fs::create_dir_all(&work).map_err(|e| e.to_string())?;

    // Written and checked in the scratch directory first, so a bad ICO never replaces the tracked
    // one that builds embed.
    let ico_result = (|| -> Result<(), String> {
        let mut pngs = Vec::new();
        for size in ICO_DIB_SIZES {
            let png = work.join(format!("{size}.png"));
            render_svg(&brand, icon_art(size), size, &png)?;
            pngs.push(png);
        }
        // ImageMagick writes every image of an `.ico` as a DIB, which is what the tray needs; the
        // PNG entry is appended afterward by `append_png_image`.
        let dib_ico = work.join("dib.ico");
        let mut ico_args: Vec<&std::ffi::OsStr> = pngs.iter().map(|p| p.as_os_str()).collect();
        ico_args.push(dib_ico.as_os_str());
        run_tool("magick", &ico_args)?;
        let large = work.join(format!("{ICO_PNG_SIZE}.png"));
        render_svg(&brand, icon_art(ICO_PNG_SIZE), ICO_PNG_SIZE, &large)?;
        let dib = std::fs::read(&dib_ico).map_err(|e| e.to_string())?;
        let png = std::fs::read(&large).map_err(|e| e.to_string())?;
        let ico = append_png_image(&dib, &png)?;
        check_icon(&ico)?;
        let target = out.join("tachyon.ico");
        std::fs::write(&target, ico).map_err(|e| format!("{}: {e}", target.display()))
    })();

    // Rendered and copied only if every asset renders, so a partial failure never leaves a stale
    // asset next to fresh ones.
    let msix_result = (|| -> Result<(), String> {
        let mut staged = Vec::new();
        let mut jobs: Vec<(String, u32, String)> = MSIX_ASSETS
            .iter()
            .map(|&(name, size)| (name.to_owned(), size, icon_art(size).to_owned()))
            .collect();
        for (asset, kind) in FILE_KINDS {
            for (qualifier, size) in FILE_SIZES {
                let name = match qualifier {
                    Some(n) => format!("{asset}.targetsize-{n}.png"),
                    None => format!("{asset}.png"),
                };
                jobs.push((name, size, file_art(kind, size)));
            }
        }
        for (name, size, art) in jobs {
            let dest = work.join(&name);
            render_svg(&brand, &art, size, &dest)?;
            staged.push((dest, name));
        }
        std::fs::create_dir_all(&msix_assets)
            .map_err(|e| format!("{}: {e}", msix_assets.display()))?;
        for (dest, name) in staged {
            let target = msix_assets.join(name);
            std::fs::copy(&dest, &target)
                .map(drop)
                .map_err(|e| format!("{}: {e}", target.display()))?;
        }
        Ok(())
    })();

    let svg = out.join("tachyon.svg");
    let svg_result = std::fs::copy(brand.join(icon_art(ICO_PNG_SIZE)), &svg)
        .map(drop)
        .map_err(|e| format!("{}: {e}", svg.display()));

    let _ = std::fs::remove_dir_all(&work);
    ico_result?;
    msix_result?;
    svg_result?;
    println!(
        "{}, {} MSIX assets in {} and {} updated",
        out.join("tachyon.ico").display(),
        MSIX_ASSETS.len() + FILE_KINDS.len() * FILE_SIZES.len(),
        msix_assets.display(),
        svg.display()
    );
    Ok(ExitCode::SUCCESS)
}

/// `ico` (images all DIBs) with `png`, a square PNG of [`ICO_PNG_SIZE`] px, added as its last
/// image. Every existing image's data moves 16 bytes further into the file, to make room for the
/// new directory entry, so their offsets are rewritten.
fn append_png_image(ico: &[u8], png: &[u8]) -> Result<Vec<u8>, String> {
    let count = ico.get(4..6).map(|b| u16::from_le_bytes([b[0], b[1]])).ok_or("truncated icon")?;
    let directory_end = 6 + 16 * usize::from(count);
    let entries = ico.get(6..directory_end).ok_or("truncated icon directory")?;
    let images = ico.get(directory_end..).ok_or("truncated icon")?;
    let mut out = Vec::with_capacity(ico.len() + 16 + png.len());
    out.extend([0, 0, 1, 0]); // reserved, type 1 (icon)
    out.extend((count + 1).to_le_bytes());
    for entry in entries.as_chunks::<16>().0 {
        let offset = u32::from_le_bytes([entry[12], entry[13], entry[14], entry[15]]);
        out.extend(&entry[..12]);
        out.extend((offset + 16).to_le_bytes());
    }
    // Width and height 0 mean 256; no palette; 1 plane; 32 bits per pixel.
    out.extend([0, 0, 0, 0, 1, 0, 32, 0]);
    out.extend((png.len() as u32).to_le_bytes());
    out.extend(((ico.len() + 16) as u32).to_le_bytes());
    out.extend(images);
    out.extend(png);
    Ok(out)
}

/// The `.ico` holds exactly [`ICO_DIB_SIZES`] as 32-bit DIBs (a `BITMAPINFOHEADER` with 32 bits
/// per pixel), in that order, then one [`ICO_PNG_SIZE`] px PNG, and every image lies inside the
/// file.
fn check_icon(ico: &[u8]) -> Result<(), String> {
    const PNG_SIGNATURE: &[u8] = b"\x89PNG\r\n\x1a\n";
    let u16_at = |at: usize| ico.get(at..at + 2).map(|b| u16::from_le_bytes([b[0], b[1]]));
    let u32_at = |at: usize| {
        ico.get(at..at + 4).map(|b| u32::from_le_bytes([b[0], b[1], b[2], b[3]]) as usize)
    };
    let count = usize::from(u16_at(4).ok_or("the icon file is truncated")?);
    let expected: Vec<u32> = ICO_DIB_SIZES.iter().copied().chain([ICO_PNG_SIZE]).collect();
    if count != expected.len() {
        return Err(format!("the icon has {count} images, expected {}", expected.len()));
    }
    for (i, &size) in expected.iter().enumerate() {
        let entry = 6 + 16 * i;
        let width = ico.get(entry).map(|&w| if w == 0 { 256 } else { u32::from(w) });
        let len = u32_at(entry + 8).ok_or("the icon directory is truncated")?;
        let offset = u32_at(entry + 12).ok_or("the icon directory is truncated")?;
        let image = ico.get(offset..offset + len).ok_or(format!("icon image {i} is truncated"))?;
        if width != Some(size) {
            return Err(format!("icon image {i} is {width:?} px wide, expected {size}"));
        }
        let is_png = image.starts_with(PNG_SIGNATURE);
        let is_dib = image.starts_with(&[40, 0, 0, 0]) && u16_at(offset + 14) == Some(32);
        if size == ICO_PNG_SIZE && !is_png {
            return Err(format!("icon image {i} ({size} px) is not a PNG"));
        }
        if size != ICO_PNG_SIZE && !is_dib {
            return Err(format!("icon image {i} ({size} px) is not a 32-bit DIB"));
        }
    }
    Ok(())
}

/// `version` from the workspace manifest's `[workspace.package]` table.
fn workspace_version(root: &Path) -> Result<String, String> {
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).map_err(|e| e.to_string())?;
    manifest
        .split("[workspace.package]")
        .nth(1)
        .and_then(|table| table.lines().find_map(|line| line.trim().strip_prefix("version = ")))
        .map(|version| version.trim_matches('"').to_owned())
        .ok_or_else(|| "no version in [workspace.package]".into())
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask is inside the workspace")
        .into()
}

fn release_binary() -> PathBuf {
    let target_dir = std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| workspace_root().join("target"));
    target_dir.join("release").join(format!("tachyon{}", std::env::consts::EXE_SUFFIX))
}

/// Converts a 3-part workspace version ("0.1.0") to the 4-part quad the MSIX manifest and
/// `.appinstaller` require ("0.1.0.0"), or validates that a 4-part override already is one.
fn to_version4(version: &str) -> Result<String, String> {
    let parts: Vec<&str> = version.split('.').collect();
    let numeric = parts.iter().all(|p| !p.is_empty() && p.bytes().all(|b| b.is_ascii_digit()));
    match parts.len() {
        3 if numeric => Ok(format!("{version}.0")),
        4 if numeric => Ok(version.to_owned()),
        _ => Err(format!("version must be 3 or 4 dot-separated numbers, got {version:?}")),
    }
}

/// Reads `Name` and `Publisher` out of the manifest template's `<Identity>` element, so
/// `Tachyon.appinstaller` never states them separately from `packaging/msix/AppxManifest.xml`
/// (Publisher must match the Azure Trusted Signing certificate subject exactly, or the MSIX
/// will not install).
fn manifest_identity(manifest: &str) -> Result<(String, String), String> {
    let start = manifest.find("<Identity").ok_or("AppxManifest.xml: no <Identity> element")?;
    let end = manifest[start..]
        .find("/>")
        .map(|i| start + i)
        .ok_or("AppxManifest.xml: <Identity> is not self-closing")?;
    let identity = &manifest[start..end];
    let attr = |name: &str| -> Result<String, String> {
        let needle = format!("{name}=\"");
        let at = identity
            .find(&needle)
            .ok_or_else(|| format!("AppxManifest.xml: <Identity> has no {name}"))?
            + needle.len();
        let rest = &identity[at..];
        let close =
            rest.find('"').ok_or_else(|| format!("AppxManifest.xml: {name} is not closed"))?;
        Ok(rest[..close].to_owned())
    };
    Ok((attr("Name")?, attr("Publisher")?))
}

/// `name` (`makeappx.exe`, `makepri.exe`) from the highest-versioned Windows 10/11 SDK under its
/// `bin` directory. The version folders are all `10.0.<5-digit build>.0`, so a plain string sort
/// of the directory names picks the newest build.
fn find_sdk_tool(name: &str) -> Result<PathBuf, String> {
    let sdk_bin = PathBuf::from(r"C:\Program Files (x86)\Windows Kits\10\bin");
    let mut versions: Vec<PathBuf> = std::fs::read_dir(&sdk_bin)
        .map_err(|e| format!("{}: {e} (install the Windows 10/11 SDK)", sdk_bin.display()))?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    versions.sort();
    versions
        .into_iter()
        .rev()
        .map(|dir| dir.join("x64").join(name))
        .find(|candidate| candidate.is_file())
        .ok_or_else(|| {
            format!("no {name} under {} (install the Windows 10/11 SDK)", sdk_bin.display())
        })
}

/// Runs an SDK tool, failing with its name when it cannot start or exits non-zero.
fn run_sdk_tool(tool: &Path, args: &[&std::ffi::OsStr]) -> Result<(), String> {
    let status =
        Command::new(tool).args(args).status().map_err(|e| format!("{}: {e}", tool.display()))?;
    if status.success() { Ok(()) } else { Err(format!("{} failed ({status})", tool.display())) }
}

/// `cargo xtask msix`: packs the signed `target/release/tachyon.exe`, `packaging/msix/Assets`
/// and the manifest (with its version filled in) into an MSIX with `makeappx.exe`, then writes
/// the `.appinstaller` that points App Installer at it for auto-update.
fn msix(args: Vec<String>) -> Result<ExitCode, String> {
    if !cfg!(windows) {
        return Err(
            "msix is only supported on Windows (it packs with makeappx.exe from the Windows \
             10/11 SDK)"
                .into(),
        );
    }
    let mut version_override = None;
    let mut appinstaller_base = None;
    let mut args = args.into_iter();
    while let Some(arg) = args.next() {
        let mut value = || args.next().ok_or_else(|| format!("{arg} needs a value"));
        match arg.as_str() {
            "--version" => version_override = Some(value()?),
            "--appinstaller-base" => appinstaller_base = Some(value()?),
            _ => return Err(format!("unknown argument {arg}\n\n{USAGE}")),
        }
    }

    let root = workspace_root();
    let version = match &version_override {
        Some(v) => to_version4(v)?,
        None => to_version4(&workspace_version(&root)?)?,
    };
    // The GitHub release tag is the version's first three parts (`v0.1.0`), even when
    // `--version` overrides the fourth part for update testing; pair that with
    // `--appinstaller-base` when the tag does not really carry this build.
    let version3 = version.rsplit_once('.').map_or(version.as_str(), |(head, _)| head);

    let exe = release_binary();
    if !exe.is_file() {
        return Err(format!(
            "{}: build and sign the release binary first (cargo build --release -p tachyon)",
            exe.display()
        ));
    }
    let dist = exe
        .parent()
        .and_then(|release| release.parent())
        .ok_or("no target directory")?
        .join("dist");
    std::fs::create_dir_all(&dist).map_err(|e| format!("{}: {e}", dist.display()))?;

    let stage = dist.join("msix-stage");
    let _ = std::fs::remove_dir_all(&stage);
    let stage_assets = stage.join("Assets");
    std::fs::create_dir_all(&stage_assets)
        .map_err(|e| format!("{}: {e}", stage_assets.display()))?;

    let manifest_path = root.join("packaging/msix/AppxManifest.xml");
    let manifest_template = std::fs::read_to_string(&manifest_path)
        .map_err(|e| format!("{}: {e}", manifest_path.display()))?;
    let (name, publisher) = manifest_identity(&manifest_template)?;
    let manifest = manifest_template.replace("{{VERSION}}", &version);
    let staged_manifest = stage.join("AppxManifest.xml");
    std::fs::write(&staged_manifest, manifest)
        .map_err(|e| format!("{}: {e}", staged_manifest.display()))?;

    std::fs::copy(&exe, stage.join("tachyon.exe"))
        .map(drop)
        .map_err(|e| format!("{}: {e}", exe.display()))?;

    let assets_src = root.join("packaging/msix/Assets");
    for entry in
        std::fs::read_dir(&assets_src).map_err(|e| format!("{}: {e}", assets_src.display()))?
    {
        let entry = entry.map_err(|e| e.to_string())?;
        let dest = stage_assets.join(entry.file_name());
        std::fs::copy(entry.path(), &dest)
            .map(drop)
            .map_err(|e| format!("{}: {e}", dest.display()))?;
    }

    // The resource index. Without `resources.pri`, Windows cannot see the `targetsize-*` and
    // `altform-unplated` icon files and uses the manifest's unqualified, plated 44 px logo
    // everywhere: the taskbar showed the large-icon art on an accent-colored square. The config
    // is written outside the staged folder so it is neither indexed nor packed.
    let makepri = find_sdk_tool("makepri.exe")?;
    let pri_config = dist.join("priconfig.xml");
    let pri_file = stage.join("resources.pri");
    let result = run_sdk_tool(
        &makepri,
        &[
            "createconfig".as_ref(),
            "/cf".as_ref(),
            pri_config.as_os_str(),
            "/dq".as_ref(),
            "en-US".as_ref(),
            "/pv".as_ref(),
            "10.0.0".as_ref(),
            "/o".as_ref(),
        ],
    )
    .and_then(|()| {
        run_sdk_tool(
            &makepri,
            &[
                "new".as_ref(),
                "/pr".as_ref(),
                stage.as_os_str(),
                "/cf".as_ref(),
                pri_config.as_os_str(),
                "/mn".as_ref(),
                staged_manifest.as_os_str(),
                "/of".as_ref(),
                pri_file.as_os_str(),
                "/o".as_ref(),
            ],
        )
    });
    let _ = std::fs::remove_file(&pri_config);
    if let Err(e) = result {
        let _ = std::fs::remove_dir_all(&stage);
        return Err(e);
    }

    let makeappx = find_sdk_tool("makeappx.exe")?;
    let package_name = format!("Tachyon_{version}_x64.msix");
    let package_path = dist.join(&package_name);
    let packed = run_sdk_tool(
        &makeappx,
        &[
            "pack".as_ref(),
            "/o".as_ref(),
            "/d".as_ref(),
            stage.as_os_str(),
            "/p".as_ref(),
            package_path.as_os_str(),
        ],
    );
    let _ = std::fs::remove_dir_all(&stage);
    packed?;

    let (self_uri, package_uri) = match &appinstaller_base {
        Some(base) => {
            let base = base.trim_end_matches('/');
            (format!("{base}/Tachyon.appinstaller"), format!("{base}/{package_name}"))
        }
        None => (
            "https://github.com/DailenG/tachyon/releases/latest/download/Tachyon.appinstaller"
                .to_owned(),
            format!(
                "https://github.com/DailenG/tachyon/releases/download/v{version3}/{package_name}"
            ),
        ),
    };
    let appinstaller = format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <AppInstaller\n    \
             xmlns=\"http://schemas.microsoft.com/appx/appinstaller/2021\"\n    \
             Version=\"{version}\"\n    \
             Uri=\"{self_uri}\">\n\n  \
           <MainPackage\n      \
               Name=\"{name}\"\n      \
               Publisher=\"{publisher}\"\n      \
               Version=\"{version}\"\n      \
               ProcessorArchitecture=\"x64\"\n      \
               Uri=\"{package_uri}\" />\n\n  \
           <UpdateSettings>\n    \
             <OnLaunch HoursBetweenUpdateChecks=\"0\" ShowPrompt=\"false\" \
             UpdateBlocksActivation=\"false\" />\n    \
             <AutomaticBackgroundTask />\n  \
           </UpdateSettings>\n\n\
         </AppInstaller>\n"
    );
    let appinstaller_path = dist.join("Tachyon.appinstaller");
    std::fs::write(&appinstaller_path, appinstaller)
        .map_err(|e| format!("{}: {e}", appinstaller_path.display()))?;

    let size_mb = |path: &Path| -> f64 {
        std::fs::metadata(path).map(|m| m.len() as f64 / 1e6).unwrap_or(0.0)
    };
    println!("{} ({:.1} MB)", package_path.display(), size_mb(&package_path));
    println!("{}", appinstaller_path.display());
    Ok(ExitCode::SUCCESS)
}

/// One launch: wall time from `spawn` to the report line, plus the in-process
/// milestones the binary printed.
struct Sample {
    external: Duration,
    marks: BTreeMap<String, Duration>,
}

fn bench_startup(args: Vec<String>) -> Result<ExitCode, String> {
    let options = parse_bench_options(args)?;
    if options.build && options.bin.is_none() {
        run_cargo(&["build", "--release", "--package", "tachyon"])?;
    }
    let bin = options.bin.clone().unwrap_or_else(release_binary);

    if options.warm {
        let samples = bench_warm(&bin, options.runs, options.gap)?;
        return Ok(report(&samples, options.budget, "receipt"));
    }
    let mut samples = Vec::with_capacity(options.runs);
    for run in 1..=options.runs {
        let sample = launch_once(&bin).map_err(|e| format!("run {run}: {e}"))?;
        samples.push(sample);
    }
    Ok(report(&samples, options.budget, "main"))
}

/// Starts a resident instance (on a private instance id, so a running
/// Tachyon is not involved), then times launches handed to it.
fn bench_warm(bin: &PathBuf, runs: usize, gap: Duration) -> Result<Vec<Sample>, String> {
    let id = format!("tachyon-bench-{}", std::process::id());
    let mut resident = Command::new(bin)
        .arg("--report-launches")
        .env("TACHYON_INSTANCE_ID", &id)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| format!("failed to launch {}: {e}", bin.display()))?;
    let stdout = resident.stdout.take().expect("stdout is piped");
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        for line in BufReader::new(stdout).lines().map_while(Result::ok) {
            if tx.send((Instant::now(), line)).is_err() {
                break;
            }
        }
    });

    let result = (|| {
        wait_for_line(&rx, "tachyon-ready")?;
        let mut samples = Vec::with_capacity(runs);
        for run in 1..=runs {
            std::thread::sleep(gap);
            let started = Instant::now();
            let status = Command::new(bin)
                .env("TACHYON_INSTANCE_ID", &id)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .status()
                .map_err(|e| format!("run {run}: failed to launch: {e}"))?;
            if !status.success() {
                return Err(format!("run {run}: launch exited with {status}"));
            }
            let (at, line) =
                wait_for_line(&rx, "tachyon-launch").map_err(|e| format!("run {run}: {e}"))?;
            samples.push(Sample { external: at - started, marks: parse_report(&line)? });
        }
        Ok(samples)
    })();
    let _ = resident.kill();
    let _ = resident.wait();
    result
}

fn wait_for_line(
    rx: &mpsc::Receiver<(Instant, String)>,
    prefix: &str,
) -> Result<(Instant, String), String> {
    let deadline = Instant::now() + RUN_TIMEOUT;
    loop {
        let left = deadline.saturating_duration_since(Instant::now());
        match rx.recv_timeout(left) {
            Ok((at, line)) if line.starts_with(prefix) => return Ok((at, line)),
            Ok(_) => continue,
            Err(_) => return Err(format!("resident instance did not print `{prefix}`")),
        }
    }
}

fn launch_once(bin: &PathBuf) -> Result<Sample, String> {
    let started = Instant::now();
    let mut child = Command::new(bin)
        .arg("--startup-report")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| format!("failed to launch {}: {e}", bin.display()))?;

    let stdout = child.stdout.take().expect("stdout is piped");
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        for line in BufReader::new(stdout).lines() {
            let Ok(line) = line else { break };
            if line.starts_with(REPORT_PREFIX) {
                let _ = tx.send((Instant::now(), line));
                break;
            }
        }
    });

    let received = rx.recv_timeout(RUN_TIMEOUT);
    let exited = wait_with_timeout(&mut child, RUN_TIMEOUT);
    let (at, line) = received
        .map_err(|_| "no startup report received (did the window fail to open?)".to_owned())?;
    if !exited {
        return Err("tachyon did not exit after reporting".into());
    }
    Ok(Sample { external: at - started, marks: parse_report(&line)? })
}

fn wait_with_timeout(child: &mut std::process::Child, timeout: Duration) -> bool {
    let deadline = Instant::now() + timeout;
    loop {
        match child.try_wait() {
            Ok(Some(_)) => return true,
            Ok(None) if Instant::now() < deadline => std::thread::sleep(Duration::from_millis(5)),
            _ => {
                let _ = child.kill();
                let _ = child.wait();
                return false;
            }
        }
    }
}

fn parse_report(line: &str) -> Result<BTreeMap<String, Duration>, String> {
    line.split_whitespace()
        .skip(1)
        .map(|field| {
            let (key, value) = field.split_once('=').ok_or_else(|| format!("bad field {field}"))?;
            let name = key.strip_suffix("_us").ok_or_else(|| format!("bad field {field}"))?;
            let us: u64 = value.parse().map_err(|e| format!("bad field {field}: {e}"))?;
            Ok((name.to_owned(), Duration::from_micros(us)))
        })
        .collect()
}

/// Nearest-rank percentile of a non-empty, sorted slice.
fn percentile(sorted: &[Duration], p: f64) -> Duration {
    let rank = ((p * sorted.len() as f64).ceil() as usize).clamp(1, sorted.len());
    sorted[rank - 1]
}

/// `marks_from` names where the in-process milestones are measured from.
fn report(samples: &[Sample], budget: Duration, marks_from: &str) -> ExitCode {
    let ms = |d: Duration| format!("{:>8.2}", d.as_secs_f64() * 1000.0);
    let mut rows: Vec<(String, Vec<Duration>)> =
        vec![("spawn -> first frame".into(), samples.iter().map(|s| s.external).collect())];
    for name in samples[0].marks.keys() {
        let values = samples.iter().filter_map(|s| s.marks.get(name).copied()).collect();
        rows.push((format!("{marks_from} -> {name}"), values));
    }

    // The first launch has the coldest caches: it gets its own column, and
    // the percentiles (and the verdict) cover the remaining runs.
    let warm = samples.len() > 1;
    let rest_of = |values: &[Duration]| {
        let mut rest = if warm { values[1..].to_vec() } else { values.to_vec() };
        rest.sort();
        rest
    };
    println!(
        "{:<24}{:>9}{:>9}{:>9}{:>9}   ({} runs, ms)",
        "metric",
        "first",
        "p50",
        "p95",
        "max",
        samples.len()
    );
    for (name, values) in &rows {
        let first = values[0];
        let rest = rest_of(values);
        println!(
            "{name:<24} {} {} {} {}",
            ms(first),
            ms(percentile(&rest, 0.50)),
            ms(percentile(&rest, 0.95)),
            ms(*rest.last().expect("non-empty"))
        );
    }

    // Same statistic as the table's p95 column for the first row.
    let p95 = percentile(&rest_of(&rows[0].1), 0.95);
    let verdict = if p95 <= budget { "PASS" } else { "FAIL" };
    let runs = if warm { format!("runs 2-{}", samples.len()) } else { "1 run".to_owned() };
    println!(
        "\n{verdict}: p95 spawn -> first frame {:.2} ms (budget {} ms, {runs})",
        p95.as_secs_f64() * 1000.0,
        budget.as_millis()
    );
    if p95 <= budget { ExitCode::SUCCESS } else { ExitCode::FAILURE }
}
